name: kasungu_routes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  location: ^7.0.1
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  http: ^1.2.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png

flutter:
  uses-material-design: true
  assets:
    - .env
