// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd7WKMEcttAhoOpywdxyAiWZmnYWzS4Os',
    appId: '1:189104060663:web:c95e4929faad6c43c8bbf2',
    messagingSenderId: '189104060663',
    projectId: 'kasungu-248c4',
    authDomain: 'kasungu-248c4.firebaseapp.com',
    storageBucket: 'kasungu-248c4.firebasestorage.app',
    measurementId: 'G-S2Q0WXVXZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyFeweOyfpw9FSpwu2Fzj5Nje1tZEBjp8',
    appId: '1:189104060663:android:e0de13bf3fb7b9bac8bbf2',
    messagingSenderId: '189104060663',
    projectId: 'kasungu-248c4',
    storageBucket: 'kasungu-248c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApUsCzZng8hPbm1cu9b_F86Ts7xP7la2c',
    appId: '1:189104060663:ios:d9f8ebc4c7f0ebf5c8bbf2',
    messagingSenderId: '189104060663',
    projectId: 'kasungu-248c4',
    storageBucket: 'kasungu-248c4.firebasestorage.app',
    iosBundleId: 'com.example.kasunguRoutes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApUsCzZng8hPbm1cu9b_F86Ts7xP7la2c',
    appId: '1:189104060663:ios:d9f8ebc4c7f0ebf5c8bbf2',
    messagingSenderId: '189104060663',
    projectId: 'kasungu-248c4',
    storageBucket: 'kasungu-248c4.firebasestorage.app',
    iosBundleId: 'com.example.kasunguRoutes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd7WKMEcttAhoOpywdxyAiWZmnYWzS4Os',
    appId: '1:189104060663:web:537617461ddbc24cc8bbf2',
    messagingSenderId: '189104060663',
    projectId: 'kasungu-248c4',
    authDomain: 'kasungu-248c4.firebaseapp.com',
    storageBucket: 'kasungu-248c4.firebasestorage.app',
    measurementId: 'G-HC3GZE2EH5',
  );
}
